services:
  # Servicio de frontend React
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  # Servicio de productos (ejemplo futuro)
  #product-service:
  #  build:
  #    context: ./services/product-service
  #    dockerfile: Dockerfile
  #  ports:
  #    - "3001:3000"
  #  environment:
  #    - NODE_ENV=production
  #  restart: unless-stopped
  #  networks:
  #    - app-network

networks:
  app-network:
    driver: bridge
